# Scenario 2: <sup>31</sup>P-NMR kinetic analysis of an enzymatic cascade reaction

## Data Modelling Notebook

---

The essential packages to work with the modelling Notebook are:

- `catalax`
- `pyenzyme`
- `matplotlib`
- `numpy`
- `scipy`

If the identifiability analysis is desired, the following package is also required:

- `identifiability`

Depending on the use case, some additional packages maybe useful:

- `pathlib`
- `rich`
- `...`

In [ ]:
import pyenzyme as pe
import scipy as sp
import numpy as np
from matplotlib import pyplot as plt
from pyenzyme.thinlayers import ThinLayerPysces

---

### Loading the EnzymeML document for PySCeS fitting

The EnzymeML document from the previous Notebook can be used directly with PySCeS for fitting the kinetic parameters of the enzymatic cascade reaction directly from PyEnzyme using the implemented thin layer interface.

#### EnzymeML document

In [ ]:
enzmldoc = pe.read_enzymeml('./data/output/pgm-eno.json')

In [ ]:
enzmldoc

In [ ]:
enzmldoc.parameters

In [ ]:
pe.summary(enzmldoc)

#### PySCeS fitting

After instantiating the PySCeS thin layer, multiple fitting algorithms that can be passed with the `method` argument to the `optimize` method are available for parameter estimation.

In [ ]:
tl_psc = ThinLayerPysces(enzmldoc=enzmldoc)

In [ ]:
res = tl_psc.optimize()

In [ ]:
res.params

In [ ]:
# other optimizer method
res2 = tl_psc.optimize(method='nelder')

In [ ]:
res2.params

The results of the fitting can be visualized using the `plot` method of PyEnzyme.

In [ ]:
f, ax = pe.plot(
    enzmldoc,
    thinlayer=tl_psc,
    show=True,
 )

### Identifyability analysis

If desired, using the Python package `identifiability`, the confidence intervals can be calculated and plotted on the basis of a profile-likelihood.  
Based on `lmfit` (including custom functions to select the range for parameter scanning and for plotting the profile likelihood), the chi-squared distribution is used to assess the significance.

In [ ]:
from identifiability import ConfidenceInterval

In [ ]:
ci = ConfidenceInterval(tl_psc.minimizer, res)

In [ ]:
# takes a while
ci.calc_all_ci(mp=False)

In [ ]:
ci.plot_all_ci()

---

### Disclosure

**Contributions**

If you wish to contribute to the EnyzmeML and/or NMRPy platforms, find us on our [EnzymeML GitHub](https://github.com/EnzymeML) and [NMRPy GitHub](https://github.com/NMRPy)!

**BSD 3-Clause License**

Copyright (c) 2026 Johann Rohwer

Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS “AS IS” AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.